/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router. Do not edit manually.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountActivityRouteImport } from './routes/account/activity'
import { Route as AccountDuplicatesRouteImport } from './routes/account/duplicates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)

const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)

const AccountActivityRoute = AccountActivityRouteImport.update({
  id: '/account/activity',
  path: '/account/activity',
  getParentRoute: () => rootRouteImport,
} as any)

const AccountDuplicatesRoute = AccountDuplicatesRouteImport.update({
  id: '/account/duplicates',
  path: '/account/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/account': typeof AccountIndexRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/duplicates': typeof AccountDuplicatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/account': typeof AccountIndexRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/duplicates': typeof AccountDuplicatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/': typeof AuthIndexRoute
  '/account/': typeof AccountIndexRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/duplicates': typeof AccountDuplicatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/account' | '/account/activity' | '/account/duplicates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/account' | '/account/activity' | '/account/duplicates'
  id: '__root__' | '/' | '/auth/' | '/account/' | '/account/activity' | '/account/duplicates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountActivityRoute: typeof AccountActivityRoute
  AccountDuplicatesRoute: typeof AccountDuplicatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/activity': {
      id: '/account/activity'
      path: '/account/activity'
      fullPath: '/account/activity'
      preLoaderRoute: typeof AccountActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/duplicates': {
      id: '/account/duplicates'
      path: '/account/duplicates'
      fullPath: '/account/duplicates'
      preLoaderRoute: typeof AccountDuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountActivityRoute: AccountActivityRoute,
  AccountDuplicatesRoute: AccountDuplicatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
