/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountDuplicatesRouteImport } from './routes/account/duplicates'
import { Route as AccountActivityRouteImport } from './routes/account/activity'

const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDuplicatesRoute = AccountDuplicatesRouteImport.update({
  id: '/account/duplicates',
  path: '/account/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountActivityRoute = AccountActivityRouteImport.update({
  id: '/account/activity',
  path: '/account/activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/duplicates': typeof AccountDuplicatesRoute
  '/account/': typeof AccountIndexRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/duplicates': typeof AccountDuplicatesRoute
  '/account': typeof AccountIndexRoute
  '/auth': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/duplicates': typeof AccountDuplicatesRoute
  '/account/': typeof AccountIndexRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/account/activity'
    | '/account/duplicates'
    | '/account/'
    | '/auth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite'
    | '/account/activity'
    | '/account/duplicates'
    | '/account'
    | '/auth'
  id:
    | '__root__'
    | '/'
    | '/invite'
    | '/account/activity'
    | '/account/duplicates'
    | '/account/'
    | '/auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviteRoute: typeof InviteRoute
  AccountActivityRoute: typeof AccountActivityRoute
  AccountDuplicatesRoute: typeof AccountDuplicatesRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/duplicates': {
      id: '/account/duplicates'
      path: '/account/duplicates'
      fullPath: '/account/duplicates'
      preLoaderRoute: typeof AccountDuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/activity': {
      id: '/account/activity'
      path: '/account/activity'
      fullPath: '/account/activity'
      preLoaderRoute: typeof AccountActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviteRoute: InviteRoute,
  AccountActivityRoute: AccountActivityRoute,
  AccountDuplicatesRoute: AccountDuplicatesRoute,
  AccountIndexRoute: AccountIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
